
# Custom NASA PROJECT CI  workflow name
name: NASA PROJECT CI
# Triggers on [ push, pull_request action ] to branch [ 21-NASA-project-CI-CD ]
on: 
  push:
    branches: [ 21-NASA-project-CI-CD ]
  pull_request:
    branches: [ 21-NASA-project-CI-CD ]

# A workflow is built up on jobs ( equivalent to checking all those jobs )
# - By default, github actions jobs runs in parallel which should be specified
#   under the job with a new indentation with `needs` key and the  action it relies
#    onto
jobs:
  build:
  # Sets custom env "variable" like
    env:
      CI: true # By default will remove watch mode if any commands has it
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
        mongodb-version: ['4.4']
    # specifies on which environment to run
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      # adding description with `name`
      - name: 'Uses Node version ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      # `run` - is to run custom command
      - run: cd 21-nasa-project-CI-CD && npm install
      - run: cd 21-nasa-project-CI-CD && npm run build --prefix client
      - run: cd 21-nasa-project-CI-CD && cd server && npm run test

